title: Sri Vishnu Totakura
description: Founding CTO and Engineer leader, Munich, Germany, Planet Earth
url: https://srivishnu.totakura.in

theme: jekyll-theme-primer

social:
  name: Sri Vishnu Totakura
  links:
    - https://github.com/tsrivishnu
    - https://www.linkedin.com/in/tsrivishnu/
